name: Deploy project to our server
on:
  push:
    branches:
      - khademul
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.thesyndicates.team
          username: thesyndicates@pmms.thesyndicates.team
          password: "!ov-MWAqVPGa)8,9"
